apiVersion: v1
kind: Service
metadata:
  name: otel-agent
  namespace: spring-app
spec:
  type: NodePort
  selector:
    app: otel-agent
  ports:
#    - name: otlp-grpc
#      port: 4317
#      targetPort: 4317
#    - name: otlp-http
#      port: 4318
#      targetPort: 4318
    - name: prometheus
      port: 8889
      targetPort: 8889

